/**
 * CURATED SEED CLINICS
 *
 * These are real, well-known youth hockey camp and clinic organizations.
 * They serve as immediate results so the app always has content,
 * even before live scraping completes or when scraping fails.
 *
 * Sources: publicly known hockey camp organizations, NHL team programs,
 * major academies, and established training companies.
 */

import { Clinic } from '@/types';

const SEED_CLINICS: Clinic[] = [
  // ── MAJOR CAMP ORGANIZATIONS ──────────────────────────────
  {
    id: 'seed-proambitions',
    name: 'Pro Ambitions Hockey Camp',
    type: 'camp',
    description: 'Elite hockey camps run by NHL alumni. Locations across the US including Boston, New York, and more.',
    longDescription: 'Pro Ambitions Hockey runs premier youth hockey camps staffed by current and former NHL, AHL, and college players. Programs include week-long day camps, elite prospect camps, and goaltending-specific sessions. Multiple locations throughout New England and beyond.',
    imageUrl: '',
    galleryUrls: [],
    location: { venue: 'Multiple Locations', address: '', city: 'Boston', state: 'MA', country: 'United States', countryCode: 'US', lat: 42.36, lng: -71.06 },
    dates: { start: '2026-06-22', end: '2026-08-21' },
    schedule: [],
    duration: '1 week per session',
    price: { amount: 695, currency: 'USD' },
    ageGroups: ['mites', 'squirts', 'peewee', 'bantam', 'midget'],
    skillLevels: ['beginner', 'intermediate', 'advanced', 'elite'],
    coaches: [{ id: 'c-pa1', name: 'NHL Alumni Staff', title: 'Head Instructors', bio: 'Former NHL, AHL, and college players', photoUrl: '', credentials: ['NHL Experience'] }],
    maxParticipants: 100,
    spotsRemaining: 40,
    registrationUrl: 'https://www.proambitions.com/',
    websiteUrl: 'https://www.proambitions.com/',
    contactEmail: '',
    contactPhone: '',
    amenities: ['Full ice sessions', 'Video analysis', 'Off-ice training'],
    includes: ['Jersey', 'Skills evaluation'],
    tags: ['summer', 'nhl-alumni', 'elite', 'boston'],
    featured: true,
    isNew: false,
    rating: 4.8,
    reviewCount: 120,
    createdAt: '2026-01-01',
    source: 'curated',
  },
  {
    id: 'seed-totalpackage',
    name: 'Total Package Hockey',
    type: 'camp',
    description: 'Year-round hockey development programs featuring skills clinics, camps, and elite training across the Northeast.',
    longDescription: 'Total Package Hockey offers comprehensive development programs for players of all skill levels. Their camps include intensive skills sessions, 3-on-3 leagues, and elite prospect development programs. Known for high-quality instruction and small group ratios.',
    imageUrl: '',
    galleryUrls: [],
    location: { venue: 'Various Rinks', address: '', city: 'New York', state: 'NY', country: 'United States', countryCode: 'US', lat: 40.71, lng: -74.01 },
    dates: { start: '2026-06-15', end: '2026-08-28' },
    schedule: [],
    duration: '1 week per session',
    price: { amount: 575, currency: 'USD' },
    ageGroups: ['squirts', 'peewee', 'bantam', 'midget'],
    skillLevels: ['intermediate', 'advanced', 'elite'],
    coaches: [{ id: 'c-tp1', name: 'Professional Coaching Staff', title: 'Director', bio: 'College and pro hockey coaches', photoUrl: '', credentials: ['USA Hockey Certified'] }],
    maxParticipants: 60,
    spotsRemaining: 25,
    registrationUrl: 'https://www.totalpackagehockey.com/',
    websiteUrl: 'https://www.totalpackagehockey.com/',
    contactEmail: '',
    contactPhone: '',
    amenities: ['Full ice', 'Shooting stations', 'Video review'],
    includes: ['Jersey', 'Player evaluation report'],
    tags: ['summer', 'skills', 'development', 'new-york'],
    featured: true,
    isNew: false,
    rating: 4.7,
    reviewCount: 85,
    createdAt: '2026-01-01',
    source: 'curated',
  },
  {
    id: 'seed-planethockey',
    name: 'Planet Hockey Skills Camps',
    type: 'camp',
    description: 'North America\'s premier hockey skills camp since 1996. Locations across the US and Canada.',
    longDescription: 'Planet Hockey has been running elite skills camps since 1996. Their unique coaching methodology focuses on developing complete players through intensive skills training, skating development, and hockey IQ. Programs available in multiple US and Canadian cities.',
    imageUrl: '',
    galleryUrls: [],
    location: { venue: 'Multiple US & Canada Locations', address: '', city: 'Minneapolis', state: 'MN', country: 'United States', countryCode: 'US', lat: 44.98, lng: -93.27 },
    dates: { start: '2026-06-08', end: '2026-08-14' },
    schedule: [],
    duration: '5 days',
    price: { amount: 849, currency: 'USD' },
    ageGroups: ['squirts', 'peewee', 'bantam', 'midget'],
    skillLevels: ['intermediate', 'advanced', 'elite'],
    coaches: [{ id: 'c-ph1', name: 'Planet Hockey Instructors', title: 'Head Coach', bio: 'Professional and college-level coaches', photoUrl: '', credentials: ['Professional Playing Experience'] }],
    maxParticipants: 48,
    spotsRemaining: 15,
    registrationUrl: 'https://www.planethockey.com/',
    websiteUrl: 'https://www.planethockey.com/',
    contactEmail: '',
    contactPhone: '',
    amenities: ['3:1 player-to-coach ratio', 'Video analysis', 'Skills competitions'],
    includes: ['Camp jersey', 'Skills report card'],
    tags: ['summer', 'skills', 'elite', 'minneapolis'],
    featured: true,
    isNew: false,
    rating: 4.9,
    reviewCount: 200,
    createdAt: '2026-01-01',
    source: 'curated',
  },
  {
    id: 'seed-laurastamm',
    name: 'Laura Stamm Power Skating',
    type: 'clinic',
    description: 'The original and most respected power skating program. Improve speed, agility, and edge work.',
    longDescription: 'Laura Stamm Power Skating is the pioneer of hockey power skating instruction. Their clinics focus exclusively on skating technique, speed, agility, crossovers, edges, and explosive starts. Available at rinks throughout the Northeast US.',
    imageUrl: '',
    galleryUrls: [],
    location: { venue: 'Various Northeast Rinks', address: '', city: 'Stamford', state: 'CT', country: 'United States', countryCode: 'US', lat: 41.05, lng: -73.54 },
    dates: { start: '2026-03-15', end: '2026-08-30' },
    schedule: [],
    duration: '2-5 days',
    price: { amount: 450, currency: 'USD' },
    ageGroups: ['squirts', 'peewee', 'bantam', 'midget', 'junior'],
    skillLevels: ['beginner', 'intermediate', 'advanced'],
    coaches: [{ id: 'c-ls1', name: 'Laura Stamm Certified Instructors', title: 'Skating Specialist', bio: 'Certified Laura Stamm Power Skating instructors', photoUrl: '', credentials: ['Laura Stamm Certified'] }],
    maxParticipants: 30,
    spotsRemaining: 12,
    registrationUrl: 'https://www.laurastamm.com/',
    websiteUrl: 'https://www.laurastamm.com/',
    contactEmail: '',
    contactPhone: '',
    amenities: ['On-ice instruction', 'Skating drills', 'Individual feedback'],
    includes: ['Skating technique manual'],
    tags: ['power-skating', 'skating', 'technique', 'stamford'],
    featured: true,
    isNew: false,
    rating: 4.9,
    reviewCount: 350,
    createdAt: '2026-01-01',
    source: 'curated',
  },
  {
    id: 'seed-img-hockey',
    name: 'IMG Academy Hockey Program',
    type: 'camp',
    description: 'World-class hockey training at the premier multi-sport complex in Bradenton, Florida.',
    longDescription: 'IMG Academy offers intensive hockey training programs combining on-ice skills, off-ice conditioning, mental toughness, and video analysis. Their state-of-the-art facility provides a unique training environment with access to strength and conditioning, sports science, and nutrition resources.',
    imageUrl: '',
    galleryUrls: [],
    location: { venue: 'IMG Academy', address: '5500 34th St W', city: 'Bradenton', state: 'FL', country: 'United States', countryCode: 'US', lat: 27.45, lng: -82.58 },
    dates: { start: '2026-06-01', end: '2026-08-15' },
    schedule: [],
    duration: '1-4 weeks',
    price: { amount: 1995, currency: 'USD' },
    ageGroups: ['peewee', 'bantam', 'midget', 'junior'],
    skillLevels: ['advanced', 'elite'],
    coaches: [{ id: 'c-img1', name: 'IMG Hockey Staff', title: 'Director of Hockey', bio: 'Former professional players and certified coaches', photoUrl: '', credentials: ['Professional Experience', 'USA Hockey Level 5'] }],
    maxParticipants: 60,
    spotsRemaining: 20,
    registrationUrl: 'https://www.imgacademy.com/sports/hockey',
    websiteUrl: 'https://www.imgacademy.com/sports/hockey',
    contactEmail: '',
    contactPhone: '',
    amenities: ['Olympic-size rink', 'Strength center', 'Sports science', 'Dining hall', 'Dorms'],
    includes: ['Lodging', 'Meals', 'Jersey', 'Performance report'],
    tags: ['summer', 'elite', 'overnight', 'florida', 'prospect'],
    featured: true,
    isNew: false,
    rating: 4.6,
    reviewCount: 90,
    createdAt: '2026-01-01',
    source: 'curated',
  },

  // ── NHL TEAM YOUTH PROGRAMS ───────────────────────────────
  {
    id: 'seed-bruins-camp',
    name: 'Boston Bruins Youth Hockey Camp',
    type: 'camp',
    description: 'Official Boston Bruins youth hockey camp at Warrior Ice Arena. Learn from Bruins coaches and alumni.',
    longDescription: 'The official Boston Bruins youth hockey camp provides young players with top-tier instruction from Bruins staff and alumni. Held at Warrior Ice Arena, the official practice facility of the Bruins, campers receive professional-level coaching in a fun, supportive environment.',
    imageUrl: '',
    galleryUrls: [],
    location: { venue: 'Warrior Ice Arena', address: '90 Legends Way', city: 'Boston', state: 'MA', country: 'United States', countryCode: 'US', lat: 42.37, lng: -71.06 },
    dates: { start: '2026-07-06', end: '2026-07-31' },
    schedule: [],
    duration: '1 week',
    price: { amount: 750, currency: 'USD' },
    ageGroups: ['mites', 'squirts', 'peewee', 'bantam'],
    skillLevels: ['beginner', 'intermediate', 'advanced'],
    coaches: [{ id: 'c-bb1', name: 'Bruins Alumni', title: 'Guest Instructors', bio: 'Former Boston Bruins players', photoUrl: '', credentials: ['NHL Experience'] }],
    maxParticipants: 80,
    spotsRemaining: 30,
    registrationUrl: 'https://www.nhl.com/bruins/community/youth-hockey',
    websiteUrl: 'https://www.nhl.com/bruins/community/youth-hockey',
    contactEmail: '',
    contactPhone: '',
    amenities: ['NHL practice facility', 'Locker rooms', 'Off-ice activities'],
    includes: ['Bruins camp jersey', 'Photo with alumni', 'Skills evaluation'],
    tags: ['summer', 'nhl', 'bruins', 'boston'],
    featured: true,
    isNew: true,
    rating: 4.8,
    reviewCount: 65,
    createdAt: '2026-02-01',
    source: 'curated',
  },
  {
    id: 'seed-leafs-camp',
    name: 'Toronto Maple Leafs Hockey Development Camp',
    type: 'camp',
    description: 'Official Leafs youth hockey development program at Ford Performance Centre.',
    longDescription: 'The Toronto Maple Leafs Hockey Development Camp offers youth players the opportunity to train at the team\'s official practice facility. Professional instruction from certified coaches with appearances by Leafs alumni. Programs for various age groups and skill levels.',
    imageUrl: '',
    galleryUrls: [],
    location: { venue: 'Ford Performance Centre', address: '', city: 'Toronto', state: 'ON', country: 'Canada', countryCode: 'CA', lat: 43.63, lng: -79.42 },
    dates: { start: '2026-07-06', end: '2026-08-14' },
    schedule: [],
    duration: '1 week',
    price: { amount: 895, currency: 'CAD' },
    ageGroups: ['mites', 'squirts', 'peewee', 'bantam', 'midget'],
    skillLevels: ['beginner', 'intermediate', 'advanced'],
    coaches: [{ id: 'c-tl1', name: 'Leafs Coaching Staff', title: 'Development Coach', bio: 'Professional development coaches', photoUrl: '', credentials: ['Hockey Canada Certified'] }],
    maxParticipants: 60,
    spotsRemaining: 22,
    registrationUrl: 'https://www.nhl.com/mapleleafs/community/hockey-development',
    websiteUrl: 'https://www.nhl.com/mapleleafs/community/hockey-development',
    contactEmail: '',
    contactPhone: '',
    amenities: ['NHL practice facility', 'Professional training'],
    includes: ['Leafs camp jersey', 'Player report'],
    tags: ['summer', 'nhl', 'leafs', 'toronto'],
    featured: true,
    isNew: true,
    rating: 4.7,
    reviewCount: 55,
    createdAt: '2026-02-01',
    source: 'curated',
  },
  {
    id: 'seed-wild-camp',
    name: 'Minnesota Wild Youth Hockey Camp',
    type: 'camp',
    description: 'Official Minnesota Wild youth hockey programs. Training at TRIA Rink and partner facilities.',
    longDescription: 'The State of Hockey brings you the official Minnesota Wild youth hockey camp. Players train at TRIA Rink and other partner facilities throughout the Twin Cities area. Instruction from Wild development coaches with special appearances by current and former players.',
    imageUrl: '',
    galleryUrls: [],
    location: { venue: 'TRIA Rink', address: '', city: 'Saint Paul', state: 'MN', country: 'United States', countryCode: 'US', lat: 44.95, lng: -93.10 },
    dates: { start: '2026-06-22', end: '2026-08-07' },
    schedule: [],
    duration: '1 week',
    price: { amount: 650, currency: 'USD' },
    ageGroups: ['mites', 'squirts', 'peewee', 'bantam'],
    skillLevels: ['beginner', 'intermediate', 'advanced'],
    coaches: [{ id: 'c-mw1', name: 'Wild Development Staff', title: 'Development Coach', bio: 'Minnesota Wild coaching staff', photoUrl: '', credentials: ['USA Hockey Certified'] }],
    maxParticipants: 80,
    spotsRemaining: 35,
    registrationUrl: 'https://www.nhl.com/wild/community/youth-hockey',
    websiteUrl: 'https://www.nhl.com/wild/community/youth-hockey',
    contactEmail: '',
    contactPhone: '',
    amenities: ['NHL practice facility', 'Wild experience'],
    includes: ['Wild camp jersey', 'Skills assessment'],
    tags: ['summer', 'nhl', 'wild', 'minnesota'],
    featured: false,
    isNew: true,
    rating: 4.7,
    reviewCount: 45,
    createdAt: '2026-02-01',
    source: 'curated',
  },

  // ── CANADIAN ACADEMIES ────────────────────────────────────
  {
    id: 'seed-okanagan',
    name: 'Okanagan Hockey Academy Summer Camp',
    type: 'camp',
    description: 'World-renowned hockey academy in British Columbia offering elite summer hockey programs.',
    longDescription: 'Okanagan Hockey Academy is one of Canada\'s most prestigious hockey development institutions. Their summer camps attract players from around the world for intensive skills development, skating, shooting, and game sense training in the beautiful Okanagan Valley.',
    imageUrl: '',
    galleryUrls: [],
    location: { venue: 'Okanagan Hockey Academy', address: '', city: 'Penticton', state: 'BC', country: 'Canada', countryCode: 'CA', lat: 49.49, lng: -119.59 },
    dates: { start: '2026-07-05', end: '2026-08-22' },
    schedule: [],
    duration: '1-3 weeks',
    price: { amount: 1495, currency: 'CAD' },
    ageGroups: ['peewee', 'bantam', 'midget', 'junior'],
    skillLevels: ['intermediate', 'advanced', 'elite'],
    coaches: [{ id: 'c-ok1', name: 'OHA Coaching Staff', title: 'Head Coach', bio: 'Professional and junior league coaches', photoUrl: '', credentials: ['Hockey Canada Level 3+'] }],
    maxParticipants: 80,
    spotsRemaining: 30,
    registrationUrl: 'https://www.okanaganhockey.com/',
    websiteUrl: 'https://www.okanaganhockey.com/',
    contactEmail: '',
    contactPhone: '',
    amenities: ['Twin rinks', 'Gym', 'Dormitory', 'Cafeteria', 'Video room'],
    includes: ['Lodging', 'Meals', 'Jersey', 'Evaluation report'],
    tags: ['summer', 'overnight', 'elite', 'canada', 'penticton'],
    featured: true,
    isNew: false,
    rating: 4.8,
    reviewCount: 180,
    createdAt: '2026-01-01',
    source: 'curated',
  },
  {
    id: 'seed-pursuit',
    name: 'Pursuit of Excellence Hockey Academy',
    type: 'camp',
    description: 'Kelowna-based hockey academy with elite summer programs and year-round training.',
    longDescription: 'Pursuit of Excellence Hockey Academy in Kelowna, BC has been developing elite hockey talent since 1994. Their summer programs combine intensive on-ice training with off-ice conditioning, mental performance, and video analysis.',
    imageUrl: '',
    galleryUrls: [],
    location: { venue: 'Pursuit of Excellence', address: '', city: 'Kelowna', state: 'BC', country: 'Canada', countryCode: 'CA', lat: 49.88, lng: -119.50 },
    dates: { start: '2026-07-06', end: '2026-08-14' },
    schedule: [],
    duration: '1-2 weeks',
    price: { amount: 1295, currency: 'CAD' },
    ageGroups: ['peewee', 'bantam', 'midget'],
    skillLevels: ['advanced', 'elite'],
    coaches: [{ id: 'c-poe1', name: 'POE Staff', title: 'Director', bio: 'WHL, AHL, and professional coaches', photoUrl: '', credentials: ['Professional Experience'] }],
    maxParticipants: 60,
    spotsRemaining: 18,
    registrationUrl: 'https://www.poehockey.com/',
    websiteUrl: 'https://www.poehockey.com/',
    contactEmail: '',
    contactPhone: '',
    amenities: ['Rink', 'Gym', 'Dormitory', 'Video analysis suite'],
    includes: ['Lodging', 'Meals', 'Evaluation'],
    tags: ['summer', 'overnight', 'elite', 'canada', 'kelowna'],
    featured: false,
    isNew: false,
    rating: 4.7,
    reviewCount: 95,
    createdAt: '2026-01-01',
    source: 'curated',
  },

  // ── EUROPEAN PROGRAMS ─────────────────────────────────────
  {
    id: 'seed-swedish-camp',
    name: 'Swedish Hockey School (Hockeyskola)',
    type: 'camp',
    description: 'Official Swedish Ice Hockey Association youth development camps across Sweden.',
    longDescription: 'The Swedish Ice Hockey Association runs hockey schools (hockeyskolor) across the country, teaching the famous Swedish style of play emphasizing skating, puck skills, creativity, and team play. Programs available for beginners through elite players.',
    imageUrl: '',
    galleryUrls: [],
    location: { venue: 'Various Swedish Rinks', address: '', city: 'Stockholm', state: '', country: 'Sweden', countryCode: 'SE', lat: 59.33, lng: 18.07 },
    dates: { start: '2026-06-15', end: '2026-08-15' },
    schedule: [],
    duration: '1 week',
    price: { amount: 4500, currency: 'SEK' },
    ageGroups: ['mites', 'squirts', 'peewee', 'bantam'],
    skillLevels: ['beginner', 'intermediate', 'advanced'],
    coaches: [{ id: 'c-se1', name: 'SHL & Allsvenskan Coaches', title: 'Head Instructor', bio: 'Coaches from Swedish professional leagues', photoUrl: '', credentials: ['Swedish Hockey Certification'] }],
    maxParticipants: 40,
    spotsRemaining: 15,
    registrationUrl: 'https://www.swehockey.se/',
    websiteUrl: 'https://www.swehockey.se/',
    contactEmail: '',
    contactPhone: '',
    amenities: ['Olympic-standard ice', 'Off-ice training'],
    includes: ['Camp jersey', 'Skills evaluation'],
    tags: ['summer', 'europe', 'sweden', 'swedish-style'],
    featured: false,
    isNew: false,
    rating: 4.6,
    reviewCount: 70,
    createdAt: '2026-01-01',
    source: 'curated',
  },
  {
    id: 'seed-finnish-camp',
    name: 'Finnish Hockey Camp (Jääkiekkoleiri)',
    type: 'camp',
    description: 'Learn the Finnish way of hockey at official Leijonat (Lions) youth development camps.',
    longDescription: 'Finland\'s national hockey program runs development camps teaching the Finnish style — known for exceptional skating, tactical intelligence, and relentless work ethic. These camps have produced numerous NHL stars and Olympic medalists.',
    imageUrl: '',
    galleryUrls: [],
    location: { venue: 'Various Finnish Arenas', address: '', city: 'Helsinki', state: '', country: 'Finland', countryCode: 'FI', lat: 60.17, lng: 24.94 },
    dates: { start: '2026-06-08', end: '2026-08-07' },
    schedule: [],
    duration: '1 week',
    price: { amount: 450, currency: 'EUR' },
    ageGroups: ['mites', 'squirts', 'peewee', 'bantam', 'midget'],
    skillLevels: ['beginner', 'intermediate', 'advanced'],
    coaches: [{ id: 'c-fi1', name: 'Liiga & Mestis Coaches', title: 'Youth Development', bio: 'Professional Finnish league coaches', photoUrl: '', credentials: ['Finnish Hockey Certified'] }],
    maxParticipants: 40,
    spotsRemaining: 20,
    registrationUrl: 'https://www.leijonat.fi/',
    websiteUrl: 'https://www.leijonat.fi/',
    contactEmail: '',
    contactPhone: '',
    amenities: ['Professional-grade ice', 'Video analysis'],
    includes: ['Camp equipment', 'Development report'],
    tags: ['summer', 'europe', 'finland', 'finnish-style'],
    featured: false,
    isNew: false,
    rating: 4.7,
    reviewCount: 55,
    createdAt: '2026-01-01',
    source: 'curated',
  },
  {
    id: 'seed-czech-camp',
    name: 'Czech Hockey Development Camp',
    type: 'camp',
    description: 'Train in the Czech tradition of technical hockey. Summer camps in Prague and beyond.',
    longDescription: 'Czech Republic has a rich hockey tradition producing legends like Jagr, Hasek, and many more. Their development camps focus on technical skills, creative playmaking, and the famous Czech puck-handling abilities.',
    imageUrl: '',
    galleryUrls: [],
    location: { venue: 'O2 Arena Training Center', address: '', city: 'Prague', state: '', country: 'Czech Republic', countryCode: 'CZ', lat: 50.08, lng: 14.44 },
    dates: { start: '2026-07-01', end: '2026-08-15' },
    schedule: [],
    duration: '1-2 weeks',
    price: { amount: 400, currency: 'EUR' },
    ageGroups: ['squirts', 'peewee', 'bantam', 'midget'],
    skillLevels: ['intermediate', 'advanced', 'elite'],
    coaches: [{ id: 'c-cz1', name: 'Extraliga Coaches', title: 'Technical Director', bio: 'Czech Extraliga and national team coaches', photoUrl: '', credentials: ['Czech Hockey Certified'] }],
    maxParticipants: 50,
    spotsRemaining: 25,
    registrationUrl: 'https://www.ceskyhokej.cz/',
    websiteUrl: 'https://www.ceskyhokej.cz/',
    contactEmail: '',
    contactPhone: '',
    amenities: ['Professional rink', 'Technical training equipment'],
    includes: ['Camp jersey', 'Technical skills report'],
    tags: ['summer', 'europe', 'czech', 'prague', 'technical'],
    featured: false,
    isNew: false,
    rating: 4.5,
    reviewCount: 40,
    createdAt: '2026-01-01',
    source: 'curated',
  },

  // ── GOALTENDING SPECIFIC ──────────────────────────────────
  {
    id: 'seed-goalie-camp',
    name: 'Mitch Korn Goaltending Academy',
    type: 'clinic',
    description: 'Elite goaltending instruction from one of the most respected goalie coaches in hockey.',
    longDescription: 'Mitch Korn is widely regarded as one of the greatest goaltending coaches in hockey history, having developed multiple Vezina Trophy winners and Stanley Cup champion goalies. His academy provides elite instruction focused on technique, positioning, mental game, and game management.',
    imageUrl: '',
    galleryUrls: [],
    location: { venue: 'Nashville Area Rinks', address: '', city: 'Nashville', state: 'TN', country: 'United States', countryCode: 'US', lat: 36.16, lng: -86.78 },
    dates: { start: '2026-07-13', end: '2026-07-24' },
    schedule: [],
    duration: '5 days',
    price: { amount: 895, currency: 'USD' },
    ageGroups: ['squirts', 'peewee', 'bantam', 'midget', 'junior'],
    skillLevels: ['intermediate', 'advanced', 'elite'],
    coaches: [{ id: 'c-mk1', name: 'Mitch Korn', title: 'Head Goaltending Coach', bio: 'Former NHL goaltending coach (Predators, Capitals)', photoUrl: '', credentials: ['NHL Goaltending Coach', 'Stanley Cup Champion'] }],
    maxParticipants: 24,
    spotsRemaining: 8,
    registrationUrl: 'https://www.nhl.com/predators/community/youth-hockey',
    websiteUrl: 'https://www.nhl.com/predators/community/youth-hockey',
    contactEmail: '',
    contactPhone: '',
    amenities: ['Small group instruction', 'Video analysis', 'Mental skills training'],
    includes: ['Goalie-specific training program', 'Video breakdown'],
    tags: ['goaltending', 'elite', 'nashville', 'nhl-coaches'],
    featured: true,
    isNew: true,
    rating: 4.9,
    reviewCount: 45,
    createdAt: '2026-01-15',
    source: 'curated',
  },

  // ── LEARN TO PLAY / BEGINNER ──────────────────────────────
  {
    id: 'seed-usah-ltp',
    name: 'USA Hockey Learn to Play Program',
    type: 'development',
    description: 'Official USA Hockey introduction program for kids ages 4-9. Equipment included!',
    longDescription: 'USA Hockey\'s official Learn to Play program is the perfect entry point for children interested in hockey. This nationwide program provides 6-8 weeks of instruction with full equipment included. Available at participating rinks across the United States.',
    imageUrl: '',
    galleryUrls: [],
    location: { venue: 'Participating Rinks Nationwide', address: '', city: 'Colorado Springs', state: 'CO', country: 'United States', countryCode: 'US', lat: 38.83, lng: -104.82 },
    dates: { start: '2026-03-01', end: '2026-12-31' },
    schedule: [],
    duration: '6-8 weeks',
    price: { amount: 199, currency: 'USD' },
    ageGroups: ['mites'],
    skillLevels: ['beginner'],
    coaches: [{ id: 'c-usah1', name: 'USA Hockey Certified Coaches', title: 'Learn to Play Instructor', bio: 'USA Hockey certified volunteer coaches', photoUrl: '', credentials: ['USA Hockey Certified', 'SafeSport Certified'] }],
    maxParticipants: 30,
    spotsRemaining: 20,
    registrationUrl: 'https://www.usahockey.com/learntoplay',
    websiteUrl: 'https://www.usahockey.com/learntoplay',
    contactEmail: '',
    contactPhone: '',
    amenities: ['Full equipment provided', 'Age-appropriate instruction'],
    includes: ['Full set of hockey equipment', 'USA Hockey membership', 'Jersey'],
    tags: ['beginner-friendly', 'learn-to-play', 'kids', 'equipment-included'],
    featured: true,
    isNew: false,
    rating: 4.8,
    reviewCount: 500,
    createdAt: '2026-01-01',
    source: 'curated',
  },
  {
    id: 'seed-hockeycanada-ip',
    name: 'Hockey Canada Initiation Program',
    type: 'development',
    description: 'Hockey Canada\'s official entry-level development program for young players across Canada.',
    longDescription: 'Hockey Canada\'s Initiation Program teaches fundamental skating and hockey skills to young players in a fun, safe environment. The program is available at local hockey associations across all Canadian provinces and territories.',
    imageUrl: '',
    galleryUrls: [],
    location: { venue: 'Local Hockey Associations', address: '', city: 'Ottawa', state: 'ON', country: 'Canada', countryCode: 'CA', lat: 45.42, lng: -75.70 },
    dates: { start: '2026-09-01', end: '2026-03-31' },
    schedule: [],
    duration: 'Full season',
    price: { amount: 350, currency: 'CAD' },
    ageGroups: ['mites', 'squirts'],
    skillLevels: ['beginner'],
    coaches: [{ id: 'c-hc1', name: 'Hockey Canada Certified Coaches', title: 'Initiation Coach', bio: 'Hockey Canada certified coaches', photoUrl: '', credentials: ['Hockey Canada Certified', 'Respect in Sport'] }],
    maxParticipants: 40,
    spotsRemaining: 25,
    registrationUrl: 'https://www.hockeycanada.ca/en-ca/hockey-programs/players',
    websiteUrl: 'https://www.hockeycanada.ca/en-ca/hockey-programs/players',
    contactEmail: '',
    contactPhone: '',
    amenities: ['Cross-ice games', 'Skills stations'],
    includes: ['Hockey Canada registration', 'Development pathway'],
    tags: ['beginner-friendly', 'learn-to-play', 'canada', 'kids'],
    featured: false,
    isNew: false,
    rating: 4.6,
    reviewCount: 200,
    createdAt: '2026-01-01',
    source: 'curated',
  },

  // ── MORE US REGIONAL ──────────────────────────────────────
  {
    id: 'seed-ne-elite',
    name: 'Northeast Elite Hockey Showcase',
    type: 'showcase',
    description: 'Premier prospect showcase for Northeast players looking for junior and college exposure.',
    longDescription: 'Northeast Elite Hockey runs showcases and prospect camps designed to give players maximum exposure to junior and college hockey scouts. Events held at premier facilities throughout New England with extensive scouting coverage.',
    imageUrl: '',
    galleryUrls: [],
    location: { venue: 'New England Sports Center', address: '', city: 'Marlborough', state: 'MA', country: 'United States', countryCode: 'US', lat: 42.35, lng: -71.55 },
    dates: { start: '2026-06-19', end: '2026-06-21' },
    schedule: [],
    duration: '3 days',
    price: { amount: 595, currency: 'USD' },
    ageGroups: ['bantam', 'midget', 'junior'],
    skillLevels: ['advanced', 'elite'],
    coaches: [{ id: 'c-ne1', name: 'College & Junior Scouts', title: 'Evaluation Staff', bio: 'Active scouts from USHL, NAHL, NCAA', photoUrl: '', credentials: ['Active Scouting Staff'] }],
    maxParticipants: 120,
    spotsRemaining: 40,
    registrationUrl: 'https://www.northeastelitehockey.com/',
    websiteUrl: 'https://www.northeastelitehockey.com/',
    contactEmail: '',
    contactPhone: '',
    amenities: ['Multiple sheets', 'Scouting reports', 'Game film'],
    includes: ['Custom jersey', 'Scouting evaluation', 'Game video'],
    tags: ['showcase', 'prospect', 'college', 'junior', 'scouting'],
    featured: true,
    isNew: true,
    rating: 4.5,
    reviewCount: 75,
    createdAt: '2026-01-15',
    source: 'curated',
  },
  {
    id: 'seed-colorado-camp',
    name: 'Colorado Avalanche Youth Hockey Camp',
    type: 'camp',
    description: 'Official Avalanche youth camp at Family Sports Center. Instruction from Avs coaching staff.',
    longDescription: 'The Colorado Avalanche Youth Hockey Camp provides young players with an unforgettable hockey experience. Held at the team\'s official practice facility, campers receive instruction from Avalanche coaches and get to meet current players.',
    imageUrl: '',
    galleryUrls: [],
    location: { venue: 'Family Sports Center', address: '', city: 'Centennial', state: 'CO', country: 'United States', countryCode: 'US', lat: 39.58, lng: -104.87 },
    dates: { start: '2026-07-13', end: '2026-07-17' },
    schedule: [],
    duration: '5 days',
    price: { amount: 725, currency: 'USD' },
    ageGroups: ['mites', 'squirts', 'peewee', 'bantam'],
    skillLevels: ['beginner', 'intermediate', 'advanced'],
    coaches: [{ id: 'c-avs1', name: 'Avalanche Staff', title: 'Camp Director', bio: 'Colorado Avalanche coaching staff', photoUrl: '', credentials: ['NHL Coaching Staff'] }],
    maxParticipants: 70,
    spotsRemaining: 28,
    registrationUrl: 'https://www.nhl.com/avalanche/community/youth-hockey',
    websiteUrl: 'https://www.nhl.com/avalanche/community/youth-hockey',
    contactEmail: '',
    contactPhone: '',
    amenities: ['NHL practice facility', 'Avalanche experience'],
    includes: ['Avs camp jersey', 'Skills evaluation', 'Player meet & greet'],
    tags: ['summer', 'nhl', 'avalanche', 'colorado'],
    featured: false,
    isNew: true,
    rating: 4.7,
    reviewCount: 50,
    createdAt: '2026-02-01',
    source: 'curated',
  },
  {
    id: 'seed-shattuck',
    name: 'Shattuck-St. Mary\'s Hockey Summer Camp',
    type: 'camp',
    description: 'Train at the prep school that produced Sidney Crosby, Jack Hughes, and many NHL stars.',
    longDescription: 'Shattuck-St. Mary\'s School in Faribault, MN is one of the most prestigious hockey prep schools in the world. Their summer camps offer players a taste of the elite training environment that has produced dozens of NHL players including Sidney Crosby, Jack Hughes, Zach Parise, and more.',
    imageUrl: '',
    galleryUrls: [],
    location: { venue: 'Shattuck-St. Mary\'s School', address: '', city: 'Faribault', state: 'MN', country: 'United States', countryCode: 'US', lat: 44.29, lng: -93.27 },
    dates: { start: '2026-06-14', end: '2026-08-07' },
    schedule: [],
    duration: '1-2 weeks',
    price: { amount: 1750, currency: 'USD' },
    ageGroups: ['peewee', 'bantam', 'midget'],
    skillLevels: ['advanced', 'elite'],
    coaches: [{ id: 'c-ssm1', name: 'SSM Hockey Staff', title: 'Head Coach', bio: 'Shattuck-St. Mary\'s coaching staff', photoUrl: '', credentials: ['Elite Prep School Coaching'] }],
    maxParticipants: 50,
    spotsRemaining: 12,
    registrationUrl: 'https://www.shattuck.org/athletics/hockey',
    websiteUrl: 'https://www.shattuck.org/athletics/hockey',
    contactEmail: '',
    contactPhone: '',
    amenities: ['Olympic ice', 'Strength center', 'Dormitory', 'Video room'],
    includes: ['Lodging', 'Meals', 'Camp gear', 'Player evaluation'],
    tags: ['summer', 'overnight', 'elite', 'prep-school', 'minnesota', 'prospect'],
    featured: true,
    isNew: false,
    rating: 4.9,
    reviewCount: 130,
    createdAt: '2026-01-01',
    source: 'curated',
  },
  {
    id: 'seed-hockey-opportunity',
    name: 'Hockey Opportunity Camp',
    type: 'camp',
    description: 'Michigan\'s premier hockey day camp since 1969. Multiple locations, all skill levels.',
    longDescription: 'Hockey Opportunity Camp has been developing young hockey players since 1969. With multiple locations throughout Michigan, they offer day camp programs for players of all abilities. Their experienced coaching staff provides personalized instruction in a fun, positive environment.',
    imageUrl: '',
    galleryUrls: [],
    location: { venue: 'Multiple Michigan Rinks', address: '', city: 'Detroit', state: 'MI', country: 'United States', countryCode: 'US', lat: 42.33, lng: -83.05 },
    dates: { start: '2026-06-15', end: '2026-08-21' },
    schedule: [],
    duration: '1 week',
    price: { amount: 495, currency: 'USD' },
    ageGroups: ['mites', 'squirts', 'peewee', 'bantam', 'midget'],
    skillLevels: ['beginner', 'intermediate', 'advanced'],
    coaches: [{ id: 'c-hoc1', name: 'HOC Coaching Staff', title: 'Camp Director', bio: '50+ years of hockey camp excellence', photoUrl: '', credentials: ['USA Hockey Certified'] }],
    maxParticipants: 100,
    spotsRemaining: 45,
    registrationUrl: 'https://www.hockeyopportunity.com/',
    websiteUrl: 'https://www.hockeyopportunity.com/',
    contactEmail: '',
    contactPhone: '',
    amenities: ['Multiple ice sessions', 'Skills stations', 'Fun activities'],
    includes: ['Camp jersey', 'Awards', 'Evaluation'],
    tags: ['summer', 'day-camp', 'michigan', 'detroit', 'beginner-friendly'],
    featured: false,
    isNew: false,
    rating: 4.6,
    reviewCount: 250,
    createdAt: '2026-01-01',
    source: 'curated',
  },

  // ── GIRLS HOCKEY ──────────────────────────────────────────
  {
    id: 'seed-girls-camp',
    name: 'USA Hockey Girls Player Development Camp',
    type: 'camp',
    description: 'Official USA Hockey development camp exclusively for female players. National team pathway.',
    longDescription: 'USA Hockey\'s Girls Player Development Camp is part of the national team development pipeline. These camps identify and develop top female talent from across the country, with instruction from Women\'s National Team coaches and players.',
    imageUrl: '',
    galleryUrls: [],
    location: { venue: 'USA Hockey Arena', address: '', city: 'Plymouth', state: 'MI', country: 'United States', countryCode: 'US', lat: 42.37, lng: -83.47 },
    dates: { start: '2026-07-20', end: '2026-07-25' },
    schedule: [],
    duration: '5 days',
    price: { amount: 550, currency: 'USD' },
    ageGroups: ['peewee', 'bantam', 'midget', 'junior'],
    skillLevels: ['advanced', 'elite'],
    coaches: [{ id: 'c-grl1', name: 'USWNT Coaches', title: 'Development Staff', bio: 'USA Women\'s National Team coaching staff', photoUrl: '', credentials: ['USA Hockey Level 5', 'National Team Staff'] }],
    maxParticipants: 80,
    spotsRemaining: 30,
    registrationUrl: 'https://www.usahockey.com/girlshockey',
    websiteUrl: 'https://www.usahockey.com/girlshockey',
    contactEmail: '',
    contactPhone: '',
    amenities: ['USA Hockey Arena', 'Off-ice training', 'Scouting'],
    includes: ['USA Hockey camp jersey', 'National team pathway evaluation'],
    tags: ['girls-hockey', 'elite', 'national-team', 'summer', 'prospect'],
    featured: true,
    isNew: true,
    rating: 4.9,
    reviewCount: 60,
    createdAt: '2026-02-01',
    source: 'curated',
  },

  // ── INTERNATIONAL / UNIQUE ────────────────────────────────
  {
    id: 'seed-intl-camp',
    name: 'International Hockey Camp (Slovakia)',
    type: 'camp',
    description: 'European-style hockey training camp in Slovakia attracting players from 20+ countries.',
    longDescription: 'The International Hockey Camp in Slovakia brings together young players from over 20 countries for a unique cross-cultural hockey experience. Training combines the best of European hockey development with world-class coaching in beautiful Slovakian facilities.',
    imageUrl: '',
    galleryUrls: [],
    location: { venue: 'Ondrej Nepela Arena', address: '', city: 'Bratislava', state: '', country: 'Slovakia', countryCode: 'SK', lat: 48.15, lng: 17.11 },
    dates: { start: '2026-07-12', end: '2026-07-25' },
    schedule: [],
    duration: '2 weeks',
    price: { amount: 750, currency: 'EUR' },
    ageGroups: ['squirts', 'peewee', 'bantam', 'midget'],
    skillLevels: ['intermediate', 'advanced', 'elite'],
    coaches: [{ id: 'c-intl1', name: 'International Coaching Staff', title: 'Camp Director', bio: 'Coaches from KHL, SHL, and other European leagues', photoUrl: '', credentials: ['IIHF Certified'] }],
    maxParticipants: 100,
    spotsRemaining: 40,
    registrationUrl: 'https://www.internationalhockeycamp.com/',
    websiteUrl: 'https://www.internationalhockeycamp.com/',
    contactEmail: '',
    contactPhone: '',
    amenities: ['Olympic rink', 'Off-ice facility', 'Cultural excursions'],
    includes: ['Lodging', 'Meals', 'Camp jersey', 'Trip activities'],
    tags: ['summer', 'overnight', 'international', 'europe', 'slovakia'],
    featured: false,
    isNew: false,
    rating: 4.5,
    reviewCount: 65,
    createdAt: '2026-01-01',
    source: 'curated',
  },
];

export default SEED_CLINICS;
