import { Clinic } from '@/types';

function c(id: string, name: string, type: Clinic['type'], desc: string, longDesc: string,
  venue: string, city: string, state: string, country: string, cc: string, lat: number, lng: number,
  start: string, end: string, dur: string, price: number, currency: string,
  ages: Clinic['ageGroups'], skills: Clinic['skillLevels'],
  coaches: { name: string; title: string }[], spots: number, spotsLeft: number,
  url: string, tags: string[], featured: boolean, isNew: boolean, rating: number, reviews: number,
): Clinic {
  return {
    id, name, type, description: desc, longDescription: longDesc,
    imageUrl: '', galleryUrls: [],
    location: { venue, address: '', city, state, country, countryCode: cc, lat, lng },
    dates: { start, end }, schedule: [], duration: dur,
    price: { amount: price, currency },
    ageGroups: ages, skillLevels: skills,
    coaches: coaches.map((coach, i) => ({ id: `${id}-c${i}`, name: coach.name, title: coach.title, bio: '', photoUrl: '', credentials: [] })),
    maxParticipants: spots, spotsRemaining: spotsLeft,
    registrationUrl: url, websiteUrl: url, contactEmail: '', contactPhone: '',
    amenities: [], includes: [], tags, featured, isNew, rating, reviewCount: reviews,
    createdAt: '2026-01-01', source: 'curated',
  };
}

const SEED_CLINICS: Clinic[] = [
  // ═══ MAX IVANOV HOCKEY (SOUTH FLORIDA — FLAGSHIP) ═══════════════
  c('seed-ivanov-elite', 'Max Ivanov Elite Hockey Academy', 'camp',
    'Premier year-round hockey development in Fort Lauderdale. Professional-level coaching for competitive players.',
    'Max Ivanov Elite Hockey Academy is South Florida\'s top hockey training program. Expert coaching staff develops players through advanced systems, video analysis, and elite-level on-ice training. Programs for travel, AAA, and junior-bound players.',
    'Baptist Health IcePlex', 'Fort Lauderdale', 'FL', 'United States', 'US', 26.12, -80.17,
    '2026-06-15', '2026-08-22', '10 weeks', 895, 'USD',
    ['squirts', 'peewee', 'bantam', 'midget'], ['advanced', 'elite'],
    [{ name: 'Max Ivanov', title: 'Head Coach & Founder' }],
    60, 18, 'https://www.maxivanovhockey.com/', ['south-florida', 'elite', 'summer', 'year-round', 'fort-lauderdale'], true, false, 4.9, 245),

  c('seed-ivanov-skills', 'Max Ivanov Summer Skills Camp', 'camp',
    'Intensive week-long skills camp at the IcePlex. Stickhandling, shooting, skating, and game IQ.',
    'Focused one-week intensive sessions covering every aspect of the game. Small group ratios ensure personalized feedback. Each session concludes with a skills combine and parent showcase.',
    'Baptist Health IcePlex', 'Fort Lauderdale', 'FL', 'United States', 'US', 26.12, -80.17,
    '2026-07-06', '2026-07-11', '1 week', 595, 'USD',
    ['mites', 'squirts', 'peewee', 'bantam'], ['beginner', 'intermediate', 'advanced'],
    [{ name: 'Max Ivanov', title: 'Head Coach' }],
    40, 12, 'https://www.maxivanovhockey.com/summer', ['summer', 'skills', 'fort-lauderdale'], true, true, 4.8, 89),

  c('seed-ivanov-goalie', 'Max Ivanov Goaltending Clinic', 'clinic',
    'Specialized goaltending clinics at the IcePlex. Positioning, angles, rebound control, and mental game.',
    'Weekly goaltending sessions led by experienced goaltending coaches. Focus on butterfly technique, post integration, tracking drills, and game-situation scenarios.',
    'Baptist Health IcePlex', 'Fort Lauderdale', 'FL', 'United States', 'US', 26.12, -80.17,
    '2026-03-01', '2026-05-31', '12 weeks', 450, 'USD',
    ['squirts', 'peewee', 'bantam', 'midget'], ['intermediate', 'advanced', 'elite'],
    [{ name: 'Max Ivanov', title: 'Head Coach' }],
    16, 5, 'https://www.maxivanovhockey.com/goalies', ['goaltending', 'fort-lauderdale', 'spring'], true, false, 4.9, 67),

  c('seed-ivanov-powerskate', 'Max Ivanov Power Skating', 'clinic',
    'Edge work and power skating sessions at the IcePlex. Build speed, agility, and explosive starts.',
    'Dedicated power skating program focusing on edge control, crossovers, transitions, and acceleration. Video analysis of skating mechanics included.',
    'Baptist Health IcePlex', 'Fort Lauderdale', 'FL', 'United States', 'US', 26.12, -80.17,
    '2026-04-01', '2026-06-15', '10 weeks', 375, 'USD',
    ['mites', 'squirts', 'peewee', 'bantam'], ['beginner', 'intermediate', 'advanced'],
    [{ name: 'Max Ivanov', title: 'Skating Director' }],
    24, 8, 'https://www.maxivanovhockey.com/skating', ['power-skating', 'fort-lauderdale', 'spring'], false, true, 4.7, 53),

  // ═══ MORE SOUTH FLORIDA ═════════════════════════════════════════
  c('seed-panthers-youth', 'Florida Panthers Youth Hockey Camp', 'camp',
    'Official Panthers youth camp at the IceDen. Learn from Panthers development coaches and alumni.',
    'The Florida Panthers organization runs week-long summer camps for youth players at their practice facility. Includes Panthers jersey, skills competitions, and meet-and-greet with current players.',
    'Florida Panthers IceDen', 'Coral Springs', 'FL', 'United States', 'US', 26.27, -80.27,
    '2026-06-22', '2026-07-03', '2 weeks', 750, 'USD',
    ['mites', 'squirts', 'peewee', 'bantam'], ['beginner', 'intermediate', 'advanced'],
    [{ name: 'Panthers Development Staff', title: 'Camp Directors' }],
    80, 30, 'https://www.nhl.com/panthers/community/youth-hockey', ['nhl', 'panthers', 'summer', 'coral-springs'], true, false, 4.6, 180),

  c('seed-bhi-development', 'Baptist Health IcePlex Development Program', 'development',
    'Year-round learn-to-play and development at Fort Lauderdale\'s premier rink. Ages 4-14.',
    'Progressive development curriculum from first-time skaters to competitive travel players. Affordable monthly programs with flexible scheduling.',
    'Baptist Health IcePlex', 'Fort Lauderdale', 'FL', 'United States', 'US', 26.12, -80.17,
    '2026-01-05', '2026-12-20', '12 months', 199, 'USD',
    ['mites', 'squirts', 'peewee'], ['beginner', 'intermediate'],
    [{ name: 'Local Coaching Staff', title: 'Development Coaches' }],
    100, 45, 'https://www.baptisthealthiceplex.com/', ['development', 'year-round', 'beginner-friendly', 'fort-lauderdale'], false, false, 4.5, 95),

  c('seed-sfha-academy', 'South Florida Hockey Academy', 'camp',
    'Advanced training academy in Coral Springs for competitive players looking to reach the next level.',
    'Intensive training combining on-ice skills, off-ice conditioning, video review, and mental performance coaching.',
    'Florida Panthers IceDen', 'Coral Springs', 'FL', 'United States', 'US', 26.27, -80.27,
    '2026-06-01', '2026-08-15', '10 weeks', 685, 'USD',
    ['peewee', 'bantam', 'midget'], ['advanced', 'elite'],
    [{ name: 'Carlos Rodriguez', title: 'Academy Director' }],
    36, 14, 'https://www.southfloridahockeyacademy.com/', ['elite', 'summer', 'south-florida'], false, false, 4.6, 42),

  c('seed-pines-clinic', 'Pines Ice Arena Youth Clinic', 'clinic',
    'Affordable weekly clinics in Pembroke Pines. Great for beginners and intermediate skaters.',
    'Drop-in weekly clinics covering basic skills through intermediate concepts. No long-term commitment required.',
    'Pines Ice Arena', 'Pembroke Pines', 'FL', 'United States', 'US', 26.01, -80.34,
    '2026-01-10', '2026-12-15', '11 months', 25, 'USD',
    ['mites', 'squirts', 'peewee'], ['beginner', 'intermediate'],
    [{ name: 'Rink Staff', title: 'Instructors' }],
    30, 20, 'https://www.pinesicearena.com/', ['clinic', 'beginner-friendly', 'pembroke-pines', 'drop-in'], false, false, 4.3, 38),

  c('seed-wpb-camp', 'Palm Beach Hockey Camp', 'camp',
    'Summer hockey camp in West Palm Beach. Full-day program with on-ice and off-ice training.',
    'Week-long day camps at the Palm Beach Skate Zone. Includes drills, scrimmages, off-ice fitness, and team-building activities.',
    'Palm Beach Skate Zone', 'West Palm Beach', 'FL', 'United States', 'US', 26.72, -80.06,
    '2026-06-15', '2026-07-25', '6 weeks', 425, 'USD',
    ['mites', 'squirts', 'peewee', 'bantam'], ['beginner', 'intermediate', 'advanced'],
    [{ name: 'Mike Sullivan', title: 'Camp Director' }],
    50, 22, 'https://www.palmbeachhockeycamp.com/', ['summer', 'west-palm-beach', 'day-camp'], false, true, 4.4, 29),

  // ═══ REST OF UNITED STATES ══════════════════════════════════════
  c('seed-proambitions', 'Pro Ambitions Hockey Camp', 'camp',
    'Elite camps run by NHL alumni across the Northeast. Boston, New York, and more.',
    'Premier youth hockey camps staffed by current and former NHL players. Week-long day camps, elite prospect camps, and goaltending sessions.',
    'Multiple Locations', 'Boston', 'MA', 'United States', 'US', 42.36, -71.06,
    '2026-06-22', '2026-08-21', '1 week per session', 695, 'USD',
    ['mites', 'squirts', 'peewee', 'bantam', 'midget'], ['beginner', 'intermediate', 'advanced', 'elite'],
    [{ name: 'NHL Alumni Staff', title: 'Head Instructors' }],
    100, 40, 'https://www.proambitions.com/', ['summer', 'nhl-alumni', 'elite', 'boston'], true, false, 4.8, 220),

  c('seed-totalpackage', 'Total Package Hockey', 'camp',
    'Year-round training programs across the US. Skills camps, elite training, and prospect showcases.',
    'Comprehensive hockey training with locations throughout the United States. Programs range from beginner to elite prospect level.',
    'Multiple Locations', 'Marlborough', 'MA', 'United States', 'US', 42.35, -71.55,
    '2026-06-15', '2026-08-15', 'Various', 550, 'USD',
    ['squirts', 'peewee', 'bantam', 'midget'], ['intermediate', 'advanced', 'elite'],
    [{ name: 'TPH Coaching Staff', title: 'Directors' }],
    60, 25, 'https://www.totalpackagehockey.com/', ['year-round', 'elite', 'prospect'], true, false, 4.7, 156),

  c('seed-mn-wild-camp', 'Minnesota Wild Youth Hockey Camp', 'camp',
    'Official Wild youth camp at TRIA Rink. Professional coaching in the State of Hockey.',
    'Minnesota Wild organization camp featuring development coaches and player appearances. Held at the team\'s practice facility.',
    'TRIA Rink', 'Saint Paul', 'MN', 'United States', 'US', 44.95, -93.10,
    '2026-07-13', '2026-07-17', '1 week', 625, 'USD',
    ['mites', 'squirts', 'peewee', 'bantam'], ['beginner', 'intermediate', 'advanced'],
    [{ name: 'Wild Development Staff', title: 'Camp Coaches' }],
    80, 35, 'https://www.nhl.com/wild/community/youth-hockey', ['nhl', 'wild', 'minnesota', 'summer'], true, false, 4.7, 142),

  c('seed-shattuck', 'Shattuck-St. Mary\'s Summer Hockey', 'camp',
    'Train at the legendary Shattuck-St. Mary\'s — alma mater of Crosby, Parise, and Zach Parise.',
    'Summer programs at the premier US hockey prep school. Elite-level training for serious players considering boarding school hockey.',
    'Shattuck-St. Mary\'s School', 'Faribault', 'MN', 'United States', 'US', 44.29, -93.27,
    '2026-06-22', '2026-07-17', '4 weeks', 2200, 'USD',
    ['peewee', 'bantam', 'midget'], ['advanced', 'elite'],
    [{ name: 'SSM Hockey Staff', title: 'Academy Coaches' }],
    48, 12, 'https://www.shattuck.org/', ['elite', 'overnight', 'boarding-school', 'prep'], true, false, 4.9, 87),

  c('seed-img-hockey', 'IMG Academy Hockey', 'camp',
    'World-class hockey training at IMG Academy in Bradenton, FL. Full athletic development.',
    'IMG Academy\'s hockey program combines on-ice skills with world-class athletic facilities including sports science, nutrition, and mental performance.',
    'IMG Academy', 'Bradenton', 'FL', 'United States', 'US', 27.46, -82.58,
    '2026-06-08', '2026-08-07', '4-8 weeks', 3500, 'USD',
    ['bantam', 'midget', 'junior'], ['advanced', 'elite'],
    [{ name: 'IMG Hockey Staff', title: 'Performance Coaches' }],
    40, 15, 'https://www.imgacademy.com/sports/hockey', ['elite', 'overnight', 'florida', 'year-round'], true, false, 4.8, 98),

  c('seed-lightning-camp', 'Tampa Bay Lightning Youth Camp', 'camp',
    'Official Lightning youth hockey camp. Train where the pros train in Tampa.',
    'Tampa Bay Lightning summer hockey camp at their practice facility. Includes Lightning jersey and player meet-and-greet.',
    'TGH Ice Plex', 'Tampa', 'FL', 'United States', 'US', 27.96, -82.46,
    '2026-06-22', '2026-06-26', '1 week', 575, 'USD',
    ['mites', 'squirts', 'peewee', 'bantam'], ['beginner', 'intermediate', 'advanced'],
    [{ name: 'Lightning Youth Staff', title: 'Camp Directors' }],
    80, 28, 'https://www.nhl.com/lightning/community/youth-hockey', ['nhl', 'lightning', 'tampa', 'summer'], true, false, 4.6, 110),

  c('seed-bruins-camp', 'Boston Bruins Youth Hockey Camp', 'camp',
    'Official Bruins youth camp at Warrior Ice Arena. The best hockey city in America.',
    'Train at the Boston Bruins practice facility with NHL development coaches. Multiple week-long sessions available.',
    'Warrior Ice Arena', 'Boston', 'MA', 'United States', 'US', 42.37, -71.10,
    '2026-07-06', '2026-07-31', '4 weeks', 699, 'USD',
    ['mites', 'squirts', 'peewee', 'bantam', 'midget'], ['beginner', 'intermediate', 'advanced'],
    [{ name: 'Bruins Development Staff', title: 'Camp Coaches' }],
    90, 32, 'https://www.nhl.com/bruins/community/youth-hockey', ['nhl', 'bruins', 'boston', 'summer'], true, false, 4.7, 195),

  c('seed-rangers-camp', 'New York Rangers Youth Camp', 'camp',
    'Rangers youth hockey at MSG Training Center. NYC hockey at its finest.',
    'Official New York Rangers youth program with elite coaching staff across the NYC metro area.',
    'MSG Training Center', 'Tarrytown', 'NY', 'United States', 'US', 41.07, -73.86,
    '2026-07-13', '2026-08-07', '4 weeks', 750, 'USD',
    ['squirts', 'peewee', 'bantam', 'midget'], ['intermediate', 'advanced', 'elite'],
    [{ name: 'Rangers Youth Staff', title: 'Development Coaches' }],
    60, 20, 'https://www.nhl.com/rangers/community/youth-hockey', ['nhl', 'rangers', 'new-york', 'summer'], true, false, 4.6, 88),

  c('seed-avalanche-camp', 'Colorado Avalanche Hockey Camp', 'camp',
    'Avs youth camp at Family Sports Center. High-altitude hockey training in Denver.',
    'Official Avalanche summer camp with appearances by current players.',
    'Family Sports Center', 'Centennial', 'CO', 'United States', 'US', 39.58, -104.87,
    '2026-06-22', '2026-07-03', '2 weeks', 625, 'USD',
    ['mites', 'squirts', 'peewee', 'bantam'], ['beginner', 'intermediate', 'advanced'],
    [{ name: 'Avalanche Youth Staff', title: 'Camp Coaches' }],
    70, 25, 'https://www.nhl.com/avalanche/community/youth-hockey', ['nhl', 'avalanche', 'colorado', 'summer'], false, false, 4.5, 72),

  c('seed-penguins-camp', 'Pittsburgh Penguins Hockey Camp', 'camp',
    'Penguins youth camp at UPMC Lemieux Sports Complex. Train like Crosby and Malkin.',
    'Official Pittsburgh Penguins youth camp at their state-of-the-art practice facility.',
    'UPMC Lemieux Sports Complex', 'Cranberry Township', 'PA', 'United States', 'US', 40.70, -80.11,
    '2026-07-06', '2026-07-17', '2 weeks', 650, 'USD',
    ['squirts', 'peewee', 'bantam', 'midget'], ['intermediate', 'advanced', 'elite'],
    [{ name: 'Penguins Development Staff', title: 'Camp Directors' }],
    60, 22, 'https://www.nhl.com/penguins/community/youth-hockey', ['nhl', 'penguins', 'pittsburgh', 'summer'], false, false, 4.7, 115),

  c('seed-laura-stamm', 'Laura Stamm Power Skating', 'clinic',
    'The original power skating program. Clinics across the US and Canada since 1971.',
    'The world\'s most recognized power skating program. Focus on stride mechanics, edge work, and explosive speed.',
    'Multiple Locations', 'Stamford', 'CT', 'United States', 'US', 41.05, -73.54,
    '2026-06-01', '2026-08-31', 'Various', 395, 'USD',
    ['squirts', 'peewee', 'bantam', 'midget'], ['intermediate', 'advanced', 'elite'],
    [{ name: 'Laura Stamm Certified Staff', title: 'Skating Instructors' }],
    30, 12, 'https://www.laurastamm.com/', ['power-skating', 'summer', 'national'], true, false, 4.8, 310),

  c('seed-michigan-dev', 'Michigan Hockey Advancement', 'camp',
    'Summer hockey camps across Michigan. Detroit, Ann Arbor, and Grand Rapids locations.',
    'Comprehensive summer programming in the hockey hotbed of Michigan.',
    'Multiple Locations', 'Ann Arbor', 'MI', 'United States', 'US', 42.28, -83.74,
    '2026-06-15', '2026-08-08', '8 weeks', 495, 'USD',
    ['mites', 'squirts', 'peewee', 'bantam', 'midget'], ['beginner', 'intermediate', 'advanced'],
    [{ name: 'Michigan Coaching Staff', title: 'Camp Directors' }],
    70, 30, 'https://www.michiganhockeyadvancement.com/', ['michigan', 'summer', 'multiple-locations'], false, false, 4.5, 68),

  c('seed-stars-camp', 'Dallas Stars Youth Hockey', 'camp',
    'Stars youth camp at the StarCenter. Hockey is growing fast in Texas.',
    'Official Dallas Stars summer hockey program with professional coaching and player appearances.',
    'StarCenter Frisco', 'Frisco', 'TX', 'United States', 'US', 33.15, -96.82,
    '2026-06-29', '2026-07-10', '2 weeks', 525, 'USD',
    ['mites', 'squirts', 'peewee', 'bantam'], ['beginner', 'intermediate', 'advanced'],
    [{ name: 'Stars Youth Staff', title: 'Development Coaches' }],
    80, 40, 'https://www.nhl.com/stars/community/youth-hockey', ['nhl', 'stars', 'texas', 'summer'], false, true, 4.4, 55),

  c('seed-la-kings-camp', 'LA Kings Summer Camp', 'camp',
    'Kings youth hockey at Toyota Sports Performance Center. SoCal hockey at its best.',
    'Official Los Angeles Kings youth camp with year-round programming.',
    'Toyota Sports Performance Center', 'El Segundo', 'CA', 'United States', 'US', 33.92, -118.39,
    '2026-06-22', '2026-07-17', '4 weeks', 625, 'USD',
    ['mites', 'squirts', 'peewee', 'bantam'], ['beginner', 'intermediate', 'advanced'],
    [{ name: 'Kings Youth Development', title: 'Camp Staff' }],
    60, 25, 'https://www.nhl.com/kings/community/youth-hockey', ['nhl', 'kings', 'california', 'summer'], false, false, 4.5, 62),

  c('seed-chicago-mission', 'Chicago Mission Hockey Camp', 'camp',
    'Elite hockey development in Chicagoland. One of the top AAA programs in the US.',
    'Summer training with one of America\'s premier AAA hockey organizations.',
    'Fifth Third Arena', 'Chicago', 'IL', 'United States', 'US', 41.88, -87.67,
    '2026-06-15', '2026-07-25', '6 weeks', 595, 'USD',
    ['squirts', 'peewee', 'bantam', 'midget'], ['advanced', 'elite'],
    [{ name: 'Mission Coaching Staff', title: 'Development Directors' }],
    48, 15, 'https://www.chicagomissionhockey.com/', ['elite', 'aaa', 'chicago', 'summer'], false, false, 4.7, 75),

  // ═══ CANADA ═════════════════════════════════════════════════════
  c('seed-leafs-camp', 'Toronto Maple Leafs Hockey Camp', 'camp',
    'Official Leafs youth hockey camp at Ford Performance Centre. Canada\'s hockey capital.',
    'Train at the Maple Leafs practice facility. Includes Leafs jersey and skills competitions.',
    'Ford Performance Centre', 'Toronto', 'ON', 'Canada', 'CA', 43.63, -79.42,
    '2026-07-06', '2026-08-14', '6 weeks', 850, 'CAD',
    ['mites', 'squirts', 'peewee', 'bantam', 'midget'], ['beginner', 'intermediate', 'advanced', 'elite'],
    [{ name: 'Leafs Development Staff', title: 'Camp Directors' }],
    100, 35, 'https://www.nhl.com/mapleleafs/community/youth-hockey', ['nhl', 'maple-leafs', 'toronto', 'summer'], true, false, 4.7, 230),

  c('seed-hc-skills', 'Hockey Canada Skills Academy', 'development',
    'Official Hockey Canada development program. The gold standard of youth hockey training.',
    'Hockey Canada\'s national skills program with certified instructors across the country.',
    'Multiple Locations', 'Ottawa', 'ON', 'Canada', 'CA', 45.42, -75.70,
    '2026-09-01', '2026-06-30', '10 months', 695, 'CAD',
    ['mites', 'squirts', 'peewee', 'bantam'], ['beginner', 'intermediate', 'advanced'],
    [{ name: 'Hockey Canada Instructors', title: 'National Coaches' }],
    200, 80, 'https://www.hockeycanada.ca/', ['hockey-canada', 'national', 'development', 'year-round'], true, false, 4.8, 350),

  c('seed-okanagan', 'Okanagan Hockey Academy', 'camp',
    'World-renowned hockey academy in Penticton, BC. Overnight camps and year-round programs.',
    'One of the world\'s top hockey academies. Athletes from 30+ countries train here.',
    'Okanagan Hockey Academy', 'Penticton', 'BC', 'Canada', 'CA', 49.49, -119.59,
    '2026-07-05', '2026-08-15', '6 weeks', 3200, 'CAD',
    ['peewee', 'bantam', 'midget', 'junior'], ['advanced', 'elite'],
    [{ name: 'OHA Coaching Staff', title: 'Academy Directors' }],
    100, 30, 'https://www.okanaganhockey.com/', ['elite', 'overnight', 'boarding', 'international'], true, false, 4.9, 185),

  c('seed-montreal-camp', 'Montreal Canadiens Hockey Camp', 'camp',
    'Habs youth camp at CN Sports Complex. Hockey tradition meets modern training.',
    'Official Canadiens youth program. Bilingual coaching in English and French.',
    'CN Sports Complex', 'Montreal', 'QC', 'Canada', 'CA', 45.50, -73.57,
    '2026-06-29', '2026-07-24', '4 weeks', 725, 'CAD',
    ['mites', 'squirts', 'peewee', 'bantam'], ['beginner', 'intermediate', 'advanced'],
    [{ name: 'Canadiens Youth Staff', title: 'Camp Coaches' }],
    80, 30, 'https://www.nhl.com/canadiens/community/youth-hockey', ['nhl', 'canadiens', 'montreal', 'summer', 'bilingual'], false, false, 4.6, 125),

  c('seed-vancouver-camp', 'Vancouver Elite Hockey', 'camp',
    'Top-tier summer hockey in Vancouver with on-ice skills and off-ice athletic development.',
    'Elite summer programming at multiple Vancouver-area rinks.',
    'Hillcrest Centre', 'Vancouver', 'BC', 'Canada', 'CA', 49.24, -123.11,
    '2026-07-06', '2026-08-14', '6 weeks', 695, 'CAD',
    ['squirts', 'peewee', 'bantam', 'midget'], ['intermediate', 'advanced', 'elite'],
    [{ name: 'BC Hockey Staff', title: 'Development Coaches' }],
    50, 18, 'https://www.vancouverelitehockey.com/', ['vancouver', 'elite', 'summer'], false, false, 4.6, 58),

  c('seed-calgary-camp', 'Calgary Flames Hockey Camp', 'camp',
    'Official Flames youth camp at WinSport. Alberta hockey excellence.',
    'Train at the official Calgary Flames development facility.',
    'WinSport', 'Calgary', 'AB', 'Canada', 'CA', 51.08, -114.20,
    '2026-07-06', '2026-07-17', '2 weeks', 595, 'CAD',
    ['mites', 'squirts', 'peewee', 'bantam'], ['beginner', 'intermediate', 'advanced'],
    [{ name: 'Flames Youth Staff', title: 'Camp Directors' }],
    70, 25, 'https://www.nhl.com/flames/community/youth-hockey', ['nhl', 'flames', 'calgary', 'summer'], false, false, 4.5, 82),

  c('seed-edmonton-camp', 'Edmonton Oilers Hockey Academy', 'camp',
    'Oilers youth hockey at Rogers Place. Train in McDavid country.',
    'Official Edmonton Oilers youth development camp with multiple summer sessions.',
    'Rogers Place Community Arena', 'Edmonton', 'AB', 'Canada', 'CA', 53.55, -113.50,
    '2026-06-29', '2026-07-24', '4 weeks', 625, 'CAD',
    ['mites', 'squirts', 'peewee', 'bantam', 'midget'], ['beginner', 'intermediate', 'advanced'],
    [{ name: 'Oilers Development Staff', title: 'Camp Coaches' }],
    80, 30, 'https://www.nhl.com/oilers/community/youth-hockey', ['nhl', 'oilers', 'edmonton', 'summer'], false, false, 4.6, 95),

  c('seed-winnipeg-camp', 'Winnipeg Jets Hockey Academy', 'camp',
    'Jets youth hockey at Bell MTS Iceplex. Manitoba\'s premier youth hockey program.',
    'Official Winnipeg Jets youth camp with on-ice and off-ice components.',
    'Bell MTS Iceplex', 'Winnipeg', 'MB', 'Canada', 'CA', 49.81, -97.19,
    '2026-07-13', '2026-07-24', '2 weeks', 495, 'CAD',
    ['mites', 'squirts', 'peewee', 'bantam'], ['beginner', 'intermediate', 'advanced'],
    [{ name: 'Jets Academy Staff', title: 'Development Coaches' }],
    60, 28, 'https://www.nhl.com/jets/community/youth-hockey', ['nhl', 'jets', 'winnipeg', 'summer'], false, true, 4.5, 48),

  c('seed-halifax-camp', 'Halifax Mooseheads Hockey Camp', 'camp',
    'East Coast hockey development in Halifax. Quality coaching in Atlantic Canada.',
    'Summer hockey camp run by the Halifax Mooseheads organization.',
    'Scotiabank Centre', 'Halifax', 'NS', 'Canada', 'CA', 44.65, -63.57,
    '2026-07-06', '2026-07-17', '2 weeks', 450, 'CAD',
    ['mites', 'squirts', 'peewee', 'bantam'], ['beginner', 'intermediate', 'advanced'],
    [{ name: 'Mooseheads Staff', title: 'Camp Coaches' }],
    50, 22, 'https://www.halifaxmooseheads.ca/', ['qmjhl', 'halifax', 'atlantic-canada', 'summer'], false, false, 4.4, 35),

  // ═══ EUROPE ═════════════════════════════════════════════════════
  c('seed-sweden-stockholm', 'Stockholm Hockey School', 'camp',
    'Premier ishockeyskola in Stockholm. Train the Swedish way — skills, creativity, and team play.',
    'Sweden\'s top youth hockey program emphasizing technical skills, creativity, and small-area games.',
    'Hovet Arena', 'Stockholm', '', 'Sweden', 'SE', 59.34, 18.08,
    '2026-06-22', '2026-08-07', '7 weeks', 6500, 'SEK',
    ['squirts', 'peewee', 'bantam', 'midget'], ['intermediate', 'advanced', 'elite'],
    [{ name: 'SHL Coaching Staff', title: 'Development Coaches' }],
    40, 15, 'https://www.stockholmhockeyschool.se/', ['sweden', 'shl', 'summer', 'european-style'], true, false, 4.8, 120),

  c('seed-sweden-gothenburg', 'Frolunda HC Hockey Camp', 'camp',
    'Train with one of Sweden\'s top development programs in Gothenburg.',
    'Frolunda HC runs summer camps for international and local youth players.',
    'Scandinavium', 'Gothenburg', '', 'Sweden', 'SE', 57.70, 11.99,
    '2026-07-06', '2026-07-24', '3 weeks', 5800, 'SEK',
    ['peewee', 'bantam', 'midget'], ['advanced', 'elite'],
    [{ name: 'Frolunda Development', title: 'Academy Coaches' }],
    36, 12, 'https://www.frolundahc.se/', ['sweden', 'shl', 'elite', 'gothenburg'], false, false, 4.7, 65),

  c('seed-finland-helsinki', 'Helsinki Hockey Academy', 'camp',
    'Finnish hockey development in Helsinki. World-class goaltending and skating.',
    'Finland produces more NHL players per capita than any country. Train at the source.',
    'Helsinki Ice Hall', 'Helsinki', '', 'Finland', 'FI', 60.19, 24.93,
    '2026-06-15', '2026-07-31', '7 weeks', 890, 'EUR',
    ['squirts', 'peewee', 'bantam', 'midget'], ['intermediate', 'advanced', 'elite'],
    [{ name: 'Liiga Development Staff', title: 'Head Coaches' }],
    40, 14, 'https://www.helsinkihockeyacademy.fi/', ['finland', 'liiga', 'summer', 'goaltending'], true, false, 4.8, 95),

  c('seed-finland-tampere', 'Tampere Ilves Hockey School', 'camp',
    'Train in Tampere, Finland\'s hockey city. Home of the 2022 World Championships.',
    'Ilves runs youth camps at the Nokia Arena practice facility.',
    'Nokia Arena Practice Rink', 'Tampere', '', 'Finland', 'FI', 61.50, 23.79,
    '2026-07-06', '2026-07-24', '3 weeks', 750, 'EUR',
    ['peewee', 'bantam', 'midget'], ['intermediate', 'advanced'],
    [{ name: 'Ilves Academy', title: 'Development Coaches' }],
    32, 10, 'https://www.ilves.com/', ['finland', 'tampere', 'summer'], false, false, 4.6, 48),

  c('seed-czech-prague', 'Prague Hockey Camp', 'camp',
    'Czech hockey tradition combined with modern training methods in Prague.',
    'Train at the facilities that produced Jagr, Hasek, and Pastrnak.',
    'O2 Arena Practice Rink', 'Prague', '', 'Czech Republic', 'CZ', 50.08, 14.44,
    '2026-07-06', '2026-07-24', '3 weeks', 750, 'EUR',
    ['squirts', 'peewee', 'bantam', 'midget'], ['intermediate', 'advanced', 'elite'],
    [{ name: 'Czech Hockey Coaches', title: 'Extraliga Staff' }],
    36, 14, 'https://www.praguehockeycamp.cz/', ['czech', 'extraliga', 'summer', 'prague'], false, false, 4.7, 58),

  c('seed-russia-moscow', 'Moscow Red Army Hockey School', 'camp',
    'Legendary Russian hockey training in Moscow. The birthplace of Soviet hockey excellence.',
    'Continuation of the famous Red Army hockey tradition with the renowned Russian training system.',
    'CSKA Ice Palace', 'Moscow', '', 'Russia', 'RU', 55.75, 37.62,
    '2026-06-15', '2026-08-15', '9 weeks', 45000, 'RUB',
    ['squirts', 'peewee', 'bantam', 'midget', 'junior'], ['intermediate', 'advanced', 'elite'],
    [{ name: 'KHL Development Staff', title: 'Academy Coaches' }],
    50, 20, 'https://www.cskahockey.ru/', ['russia', 'khl', 'summer', 'moscow'], true, false, 4.7, 72),

  c('seed-swiss-davos', 'Davos Hockey Camp', 'camp',
    'Summer hockey camp in the Swiss Alps. Train at the home of the Spengler Cup.',
    'HC Davos runs international youth camps at their alpine facility.',
    'Eisstadion Davos', 'Davos', '', 'Switzerland', 'CH', 46.80, 9.84,
    '2026-07-13', '2026-07-31', '3 weeks', 1800, 'CHF',
    ['peewee', 'bantam', 'midget'], ['intermediate', 'advanced', 'elite'],
    [{ name: 'HC Davos Youth', title: 'Camp Directors' }],
    30, 10, 'https://www.hcdavos.ch/', ['switzerland', 'alps', 'summer', 'international'], true, false, 4.8, 42),

  c('seed-germany-munich', 'Munich EHC Hockey School', 'camp',
    'Eishockey Camp in Munich. Germany\'s growing hockey scene with DEL-level coaching.',
    'Red Bull Munchen\'s youth development camp.',
    'Olympia Eishalle', 'Munich', '', 'Germany', 'DE', 48.17, 11.55,
    '2026-07-06', '2026-07-24', '3 weeks', 695, 'EUR',
    ['squirts', 'peewee', 'bantam', 'midget'], ['intermediate', 'advanced'],
    [{ name: 'DEL Coaching Staff', title: 'Youth Developers' }],
    40, 18, 'https://www.redbullmuenchen.de/', ['germany', 'del', 'summer', 'munich'], false, false, 4.5, 38),

  c('seed-germany-berlin', 'Berlin Eisbaren Hockey Academy', 'camp',
    'Train with the Eisbaren Berlin, Germany\'s most successful hockey club.',
    'Summer youth camps combining German hockey tradition with modern international methods.',
    'Mercedes-Benz Arena Practice Rink', 'Berlin', '', 'Germany', 'DE', 52.51, 13.45,
    '2026-06-29', '2026-07-17', '3 weeks', 650, 'EUR',
    ['squirts', 'peewee', 'bantam'], ['beginner', 'intermediate', 'advanced'],
    [{ name: 'Eisbaren Youth Staff', title: 'Academy Coaches' }],
    36, 16, 'https://www.eisbaeren.de/', ['germany', 'del', 'berlin', 'summer'], false, true, 4.4, 28),

  c('seed-norway-oslo', 'Oslo Hockey Development Camp', 'camp',
    'Ishockey camp in Oslo. Norwegian hockey produces more NHL talent every year.',
    'Summer development camp at Jordal Amfi, Norway\'s most historic hockey venue.',
    'Jordal Amfi', 'Oslo', '', 'Norway', 'NO', 59.91, 10.78,
    '2026-07-06', '2026-07-17', '2 weeks', 5500, 'NOK',
    ['squirts', 'peewee', 'bantam', 'midget'], ['intermediate', 'advanced'],
    [{ name: 'Norwegian Hockey Staff', title: 'National Coaches' }],
    30, 12, 'https://www.hockey.no/', ['norway', 'summer', 'oslo'], false, false, 4.5, 32),

  c('seed-denmark-copenhagen', 'Copenhagen Ice Hockey School', 'camp',
    'Danish ishockey camp in Copenhagen. Growing hockey culture in Scandinavia.',
    'Summer camps at Denmark\'s premier hockey facilities.',
    'Rodovre Centrum Arena', 'Copenhagen', '', 'Denmark', 'DK', 55.68, 12.46,
    '2026-07-06', '2026-07-17', '2 weeks', 4500, 'DKK',
    ['mites', 'squirts', 'peewee', 'bantam'], ['beginner', 'intermediate', 'advanced'],
    [{ name: 'Danish Hockey Staff', title: 'Camp Coaches' }],
    30, 15, 'https://www.ishockey.dk/', ['denmark', 'summer', 'copenhagen'], false, true, 4.3, 22),

  c('seed-austria-vienna', 'Vienna Capitals Hockey Camp', 'camp',
    'Eishockey Camp in Vienna. Austria\'s top club trains the next generation.',
    'Vienna Capitals summer youth camp at the Erste Bank Arena facility.',
    'Erste Bank Arena', 'Vienna', '', 'Austria', 'AT', 48.21, 16.41,
    '2026-07-13', '2026-07-24', '2 weeks', 595, 'EUR',
    ['squirts', 'peewee', 'bantam'], ['intermediate', 'advanced'],
    [{ name: 'Capitals Youth Staff', title: 'Camp Coaches' }],
    30, 12, 'https://www.vienna-capitals.at/', ['austria', 'summer', 'vienna'], false, false, 4.4, 25),

  c('seed-uk-london', 'London Ice Hockey Academy', 'camp',
    'EIHL-level coaching in London. The UK\'s fastest growing winter sport.',
    'Summer development at Lee Valley Ice Centre. British hockey is growing rapidly.',
    'Lee Valley Ice Centre', 'London', '', 'United Kingdom', 'GB', 51.56, -0.02,
    '2026-07-06', '2026-08-14', '6 weeks', 495, 'GBP',
    ['mites', 'squirts', 'peewee', 'bantam'], ['beginner', 'intermediate', 'advanced'],
    [{ name: 'EIHL Coaching Staff', title: 'Development Coaches' }],
    40, 20, 'https://www.londonicehockeyacademy.co.uk/', ['uk', 'london', 'summer', 'eihl'], false, false, 4.3, 35),

  c('seed-france-paris', 'Paris Hockey Club Camp', 'camp',
    'Stage de hockey sur glace a Paris. French hockey growing with increasing talent.',
    'Summer hockey camp with instruction in French and English.',
    'Accor Arena Practice Rink', 'Paris', '', 'France', 'FR', 48.84, 2.38,
    '2026-07-06', '2026-07-17', '2 weeks', 550, 'EUR',
    ['squirts', 'peewee', 'bantam'], ['intermediate', 'advanced'],
    [{ name: 'French Hockey Staff', title: 'Ligue Magnus Coaches' }],
    30, 14, 'https://www.hockeyfrance.com/', ['france', 'paris', 'summer', 'bilingual'], false, false, 4.3, 20),

  c('seed-latvia-riga', 'Dinamo Riga Hockey School', 'camp',
    'Latvian hockey excellence in Riga. A proud hockey nation with deep tradition.',
    'Dinamo Riga runs summer youth camps at the Arena Riga.',
    'Arena Riga', 'Riga', '', 'Latvia', 'LV', 56.95, 24.12,
    '2026-07-06', '2026-07-24', '3 weeks', 450, 'EUR',
    ['squirts', 'peewee', 'bantam', 'midget'], ['intermediate', 'advanced'],
    [{ name: 'Dinamo Riga Youth', title: 'Academy Staff' }],
    36, 15, 'https://www.dinamoriga.lv/', ['latvia', 'riga', 'summer', 'khl'], false, false, 4.5, 30),

  // ═══ ASIA / OCEANIA / OTHER ═════════════════════════════════════
  c('seed-japan-tokyo', 'Tokyo Ice Hockey Academy', 'camp',
    'Japanese hockey development in Tokyo. Precision, discipline, and skill.',
    'Summer hockey camp at Meiji Jingu Gaien Ice Rink.',
    'Meiji Jingu Gaien Ice Rink', 'Tokyo', '', 'Japan', 'JP', 35.67, 139.72,
    '2026-07-20', '2026-08-14', '4 weeks', 85000, 'JPY',
    ['squirts', 'peewee', 'bantam'], ['intermediate', 'advanced'],
    [{ name: 'JIHF Coaching Staff', title: 'National Coaches' }],
    30, 12, 'https://www.jihf.or.jp/', ['japan', 'tokyo', 'summer', 'asia'], false, false, 4.5, 22),

  c('seed-korea-seoul', 'Seoul Ice Hockey Camp', 'camp',
    'South Korean hockey booming after the 2018 Olympics. World-class Seoul facilities.',
    'Post-Olympics hockey boom in Korea. Summer camps with national team coaches.',
    'Mokdong Ice Rink', 'Seoul', '', 'South Korea', 'KR', 37.53, 126.87,
    '2026-07-13', '2026-08-07', '4 weeks', 850000, 'KRW',
    ['squirts', 'peewee', 'bantam', 'midget'], ['beginner', 'intermediate', 'advanced'],
    [{ name: 'Korean Hockey Staff', title: 'National Coaches' }],
    40, 18, 'https://www.kiha.or.kr/', ['south-korea', 'seoul', 'summer', 'asia'], false, true, 4.3, 18),

  c('seed-china-beijing', 'Beijing Hockey Academy', 'camp',
    'Chinese hockey development post-2022 Olympics. Massive youth hockey investment.',
    'China invested billions in hockey for the 2022 Olympics. Legacy programs continue.',
    'National Aquatics Center Ice Rink', 'Beijing', '', 'China', 'CN', 39.99, 116.39,
    '2026-07-06', '2026-08-14', '6 weeks', 8500, 'CNY',
    ['mites', 'squirts', 'peewee', 'bantam'], ['beginner', 'intermediate', 'advanced'],
    [{ name: 'CIHA Development Staff', title: 'National Coaches' }],
    60, 30, 'https://www.chinaiha.com/', ['china', 'beijing', 'summer', 'asia'], false, false, 4.2, 15),

  c('seed-australia-melbourne', 'Melbourne Ice Hockey Camp', 'camp',
    'Australian ice hockey development in Melbourne. The southern hemisphere\'s hockey hub.',
    'AIHL-affiliated summer camp at O\'Brien Group Arena.',
    'O\'Brien Group Arena', 'Melbourne', 'VIC', 'Australia', 'AU', -37.82, 144.95,
    '2026-01-05', '2026-01-30', '4 weeks', 695, 'AUD',
    ['mites', 'squirts', 'peewee', 'bantam'], ['beginner', 'intermediate', 'advanced'],
    [{ name: 'AIHL Development Staff', title: 'Camp Coaches' }],
    30, 14, 'https://www.melbourneice.com.au/', ['australia', 'melbourne', 'summer', 'southern-hemisphere'], false, false, 4.3, 20),

  c('seed-australia-sydney', 'Sydney Ice Dogs Hockey Camp', 'camp',
    'Hockey development in Sydney with AIHL coaching staff.',
    'Sydney Ice Dogs run off-season youth clinics during the Australian summer.',
    'Macquarie Ice Rink', 'Sydney', 'NSW', 'Australia', 'AU', -33.78, 151.12,
    '2026-01-12', '2026-02-06', '4 weeks', 650, 'AUD',
    ['mites', 'squirts', 'peewee', 'bantam'], ['beginner', 'intermediate'],
    [{ name: 'Ice Dogs Staff', title: 'Development Coaches' }],
    25, 12, 'https://www.sydneyicedogs.com.au/', ['australia', 'sydney', 'summer', 'southern-hemisphere'], false, true, 4.2, 14),

  c('seed-uae-dubai', 'Dubai Ice Hockey Academy', 'camp',
    'Year-round ice hockey in the desert. Dubai\'s growing hockey community.',
    'Ice hockey at the state-of-the-art Dubai Ice Rink with international coaching.',
    'Dubai Ice Rink', 'Dubai', '', 'United Arab Emirates', 'AE', 25.20, 55.28,
    '2026-06-01', '2026-08-31', '3 months', 3500, 'AED',
    ['mites', 'squirts', 'peewee', 'bantam'], ['beginner', 'intermediate', 'advanced'],
    [{ name: 'International Staff', title: 'Development Directors' }],
    30, 15, 'https://www.dubaiicerink.com/', ['uae', 'dubai', 'year-round', 'international'], false, false, 4.4, 25),

  c('seed-singapore', 'Singapore Ice Hockey Club Camp', 'clinic',
    'Tropical hockey development in Singapore. Growing hockey in Southeast Asia.',
    'The Rink at JCube hosts Singapore\'s premier youth hockey programs.',
    'The Rink', 'Singapore', '', 'Singapore', 'SG', 1.33, 103.74,
    '2026-06-15', '2026-07-31', '7 weeks', 1200, 'SGD',
    ['mites', 'squirts', 'peewee'], ['beginner', 'intermediate'],
    [{ name: 'SIHF Staff', title: 'Development Coaches' }],
    20, 10, 'https://www.therink.sg/', ['singapore', 'asia', 'summer', 'tropical'], false, true, 4.1, 10),

  // ═══ SPECIALTY / SHOWCASE ═══════════════════════════════════════
  c('seed-usntdp', 'USA Hockey NTDP Evaluation Camp', 'showcase',
    'National Team Development Program evaluation. The pathway to USA Hockey\'s elite program.',
    'USA Hockey\'s pipeline for the national team. Scouts evaluate top players for potential inclusion.',
    'USA Hockey Arena', 'Plymouth', 'MI', 'United States', 'US', 42.37, -83.47,
    '2026-06-01', '2026-06-05', '5 days', 395, 'USD',
    ['bantam', 'midget'], ['elite'],
    [{ name: 'NTDP Coaching Staff', title: 'National Team Coaches' }],
    120, 0, 'https://www.usahockey.com/ntdp', ['showcase', 'elite', 'national-team', 'scouting'], true, false, 4.9, 450),

  c('seed-brick-tournament', 'Brick Invitational Hockey Tournament', 'tournament',
    'The legendary Brick tournament in Edmonton. The world\'s most prestigious minor hockey tournament.',
    'Annual Gretzky-hosted tournament for the top teams from around the world.',
    'West Edmonton Mall Ice Palace', 'Edmonton', 'AB', 'Canada', 'CA', 53.52, -113.62,
    '2026-07-01', '2026-07-05', '5 days', 0, 'CAD',
    ['mites', 'squirts'], ['elite'],
    [{ name: 'Tournament Staff', title: 'Event Directors' }],
    200, 0, 'https://www.brickhockey.com/', ['tournament', 'elite', 'edmonton', 'international', 'prestigious'], true, false, 5.0, 500),

  c('seed-planet-hockey', 'Planet Hockey International Camp', 'camp',
    'Multi-location international hockey camps. Train in the US, Canada, and Europe.',
    'Premium international camps with travel opportunities across multiple countries.',
    'Multiple Locations', 'Boston', 'MA', 'United States', 'US', 42.36, -71.06,
    '2026-06-22', '2026-08-14', 'Various', 1200, 'USD',
    ['squirts', 'peewee', 'bantam', 'midget'], ['intermediate', 'advanced', 'elite'],
    [{ name: 'Planet Hockey Staff', title: 'International Coaches' }],
    50, 18, 'https://www.planethockey.com/', ['international', 'multi-location', 'summer', 'travel'], true, false, 4.7, 130),

  c('seed-girls-showcase', 'She Shoots She Scores Girls Hockey Showcase', 'showcase',
    'Premier girls-only hockey showcase. Empowering female players across North America.',
    'Dedicated showcase for female hockey players with college scouts in attendance.',
    'Various Locations', 'Boston', 'MA', 'United States', 'US', 42.36, -71.06,
    '2026-07-18', '2026-07-20', '3 days', 350, 'USD',
    ['peewee', 'bantam', 'midget', 'junior'], ['advanced', 'elite'],
    [{ name: 'Showcase Staff', title: 'Event Directors' }],
    200, 60, 'https://www.girlshockeyshowcase.com/', ['girls-hockey', 'showcase', 'scouting', 'college'], false, true, 4.6, 55),
];

export default SEED_CLINICS;
